require:
  - rubocop
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - bin/*
    - Guardfile
    - vendor/**/*
    - config.ru
    - spec/dummy/**/*
    - tmp/**/*

Style/Documentation:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  IgnoredMethods: [
      'describe',
      'xdescribe',
      'context',
      'xcontext',
      'it',
      'xit',
      'let',
      'before',
      'after',
      'aggregate_failures',
      'scenario',
      'xscenario'
  ]

Metrics/ClassLength:
  Max: 150

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

RSpec/MultipleExpectations:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - lib/generators/ez/status/install_generator.rb
    - lib/generators/ez/status/migrations_generator.rb
